config/routes.rb
Rails.application.routes.draw do

	root 'blogs#index'

	devise_for :users, controllers: {registrations: "users/registrations"}
	
	resources :blogs do
		member do
			resources :comments do
				get :view_replies
			end
			post :upvote
		end

		collection do
			get :my_blogs
		end
	end
end

app/models/blog/comment.rb
class Blog::Comment < Comment
end

app/models/comment.rb
class Comment < ApplicationRecord
	MAX_LEVEL = 5
	before_validation :set_level
	validates :level, inclusion: 0..MAX_LEVEL
	#
	# associations
	#
	has_many :comments,:as => :commentable,:class_name => "Comment",:dependent => :destroy
	belongs_to :user, foreign_key: :commentor_id, class_name: "User"
	belongs_to :commentable, polymorphic: true
    belongs_to :source, :class_name => "Blog", :foreign_key => 'source_id'
	belongs_to :master_comment, :class_name => "Comment", :foreign_key => 'master_comment_id', optional: true
    has_many :replies, :as => :commentable,   :class_name => "Comment::Reply", :dependent => :destroy
    validates :body, :presence => {message: "Please enter comment"}

    scope :as_created, -> { order(created_at: :desc)}
    def momentize
		self.try(:created_at).try(:iso8601)
	end

	private

	def set_level
		if self.commentable.is_a?(self.class)
			self.level = self.commentable.level.next
		end
	end
end

app/models/comment/reply.rb
class Comment::Reply < Comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = @blog.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @blog.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.source_id = @blog.id
    @comment.user = current_user
    if @comment.commentable.is_a?(Comment)
      @comments = @comment.commentable.replies.as_created
    else
      @comment.commentable = @blog 
      @comments = @blog.comments.as_created 
    end

    respond_to do |format|
      if @comment.save
        @comment = Comment.new(
            commentable_id: @comment.commentable_id , 
            commentable_type: 'Comment'
        )
        format.html { redirect_to comments_path, notice: 'Comment was successfully created.' }
        format.js { render :create }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.js { render :create }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def view_replies
    @comment = Comment.where(id: params[:comment_id] ,source_id: @blog.id ).first
    @target = Comment.new(
        commentable_id: @comment.id , 
        commentable_type: 'Comment'
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @blog.comments.find(params[:id])
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :commentable_id, :commentable_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.js.erb
<%
	html  = escape_javascript(
		render 'comments/partials/nested_replies', 
		comment: @comment,
		replies: @comments , 
		blog: @blog 
	)
%>
<% if @comment.commentable.is_a?(Comment)  %>
    $('#c-reply-<%= @comment.commentable.id %>').html("<%= html %>");
<% else %>
    $('#comments-<%= @blog.id %>').html("<%= html %>");
<% end %>

$(document).trigger('init-momentize');  

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'comments/partials/form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%= render "blogs/partials/blog", blog: @blog %>
<div class="commentWrap" >
	<div class="commentData" id=comments-<%=@blog.id%>>
	    <%= render("comments/partials/nested_replies", 
	  		comment: Comment.new , 
	  		replies: @blog.comments.as_created, 
	  		blog: @blog) 
	  	%>
	</div>
</div>

<!-- End middle Section -->

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'comments/partials/form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/view_replies.js.erb
<%
	html  = escape_javascript(
		render 'comments/partials/nested_replies', 
		comment: @target,
		replies: @comment.replies , 
		blog: @blog 
	)
%>

$('#c-reply-<%= @comment.id %>').html("<%= html %>");
$(document).trigger('init-momentize');  