config/routes.rb
Rails.application.routes.draw do

	root 'blogs#index'

	devise_for :users, controllers: {registrations: "users/registrations"}
	
	resources :blogs do
		member do
			resources :comments do
				get :view_replies
			end
			post :upvote
		end

		collection do
			get :my_blogs
		end
	end
end

app/models/blog/comment.rb
class Blog::Comment < Comment
end

app/models/comment.rb
class Comment < ApplicationRecord
	MAX_LEVEL = 5
	before_validation :set_level
	validates :level, inclusion: 0..MAX_LEVEL
	#
	# associations
	#
	has_many :comments,:as => :commentable,:class_name => "Comment",:dependent => :destroy
	belongs_to :user, foreign_key: :commentor_id, class_name: "User"
	belongs_to :commentable, polymorphic: true
    belongs_to :source, :class_name => "Blog", :foreign_key => 'source_id'
	belongs_to :master_comment, :class_name => "Comment", :foreign_key => 'master_comment_id', optional: true
    has_many :replies, :as => :commentable,   :class_name => "Comment::Reply", :dependent => :destroy
    validates :body, :presence => {message: "Please enter comment"}

    scope :as_created, -> { order(created_at: :desc)}
    def momentize
		self.try(:created_at).try(:iso8601)
	end

	private

	def set_level
		if self.commentable.is_a?(self.class)
			self.level = self.commentable.level.next
		end
	end
end

app/models/comment/reply.rb
class Comment::Reply < Comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = @blog.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @blog.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.source_id = @blog.id
    @comment.user = current_user
    if @comment.commentable.is_a?(Comment)
      @comments = @comment.commentable.replies.as_created
    else
      @comment.commentable = @blog 
      @comments = @blog.comments.as_created 
    end

    respond_to do |format|
      if @comment.save
        @comment = Comment.new(
            commentable_id: @comment.commentable_id , 
            commentable_type: 'Comment'
        )
        format.html { redirect_to comments_path, notice: 'Comment was successfully created.' }
        format.js { render :create }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.js { render :create }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def view_replies
    @comment = Comment.where(id: params[:comment_id] ,source_id: @blog.id ).first
    @target = Comment.new(
        commentable_id: @comment.id , 
        commentable_type: 'Comment'
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @blog.comments.find(params[:id])
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :commentable_id, :commentable_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/partials/_form.html.erb
<div id="new-post-comment" class="ShareYourComments ShareWithMyFans hide_content">
    <%= form_for comment, url: comments_path(@blog), method: :post, remote: true do |f| %>
      <%= f.hidden_field :commentable_id %>
      <%= f.hidden_field :commentable_type %>
      <%= f.text_field :body,placeholder: "Share Your Comment...", id: "editable", class: "comment-post-corner"  %>
      <% if comment.errors.any? %>
	    <div class="error_explanation">
	      <% comment.errors.messages.each do |key, message| %>
	        <%= message.join(", ") %>
	      <% end %>
	    </div>
	   <% end%>
      <button class="ShareC" type="submit">Share</button>
    <% end %>
</div>

app/views/comments/partials/_nested_replies.html.erb
<%= render 'comments/partials/form', comment: comment , blog: blog %>
<% replies.each do |reply| %>
	<div class="commentData" id='<%= "comment-replies-#{reply.id}" %>'>
		<%= render 'comments/partials/nested_reply', reply: reply, comment: comment, blog: blog %>
	</div>
<% end %>

app/views/comments/partials/_nested_reply.html.erb
<div class="userPic">
	<%= image_tag reply.user.image_url %>
</div>
<div class="userInfo">
	<span class="post-user-first_name">
		<%= link_to "javascript:void(0);" do %>
			<%= reply.user.first_name %>
		<% end %>
	</span>
	<span class="post-user-last_name">
		<%= "@#{reply.user.last_name}" %>
	</span>
	<div class="comment-stamp-data">
		<%= content_tag :span, class: "comment-timestamp", data: {momentize: reply.momentize, image: image_url("dot-pic.png")}  do %>
		<% end %>
	</div>
</div>

<div class="commentsBody" >
	<%= content_tag :p, class: "content-post-text" do %>
		<%= shorten_link_new(reply.body.to_s.html_safe) %>
	<% end %>
	<% replies_count = reply.replies.count %>
	<li class="comment" id="c-reply-<%= reply.id %>" >
		<% if reply.id && reply.level < Comment::MAX_LEVEL %>
			<%= link_to comment_view_replies_path(blog, comment_id: reply.id), method: :get, remote: true do%>
					<span class="rplySpan">
						<%= replies_count > 0 ? pluralize(reply.replies.count, "Reply") : "Reply"  %>
					</span>
			<% end %>
		<% end%>
    </li>
</div>