config/routes.rb
Rails.application.routes.draw do

	root 'blogs#index'

	devise_for :users, controllers: {registrations: "users/registrations"}
	
	resources :blogs do
		member do
			resources :comments do
				get :view_replies
			end
			post :upvote
		end

		collection do
			get :my_blogs
		end
	end
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <%= link_to root_url, class: "head-logo" do %>
      Blogger
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div id="collapsibleNavbar" class="collapse navbar-collapse justify-content-end">
      <ul class="nav navbar-nav navbar-right">
        <li class="active nav-item"><a class="nav-link" href="/">Home</a></li>
        <% if user_signed_in? %>
          
          <li class="nav-item">
            <%= link_to 'New Blog', new_blog_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'My blogs', my_blogs_blogs_path, class: "nav-link" %>
          </li>
          
        <% else %>
         <li class="nav-item">
           <%= link_to "Login", new_user_session_path , class: "nav-link" %>
         </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_meta.html.erb
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700,700i,800" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Playfair+Display:400i,700,700i,900,900i" rel="stylesheet">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="<%= content_for?(:description) ? content_for(:description) : "BloggerApp description" %>">
<meta name="theme-color" content="#922d7b" />
<meta name="msapplication-navbutton-color" content="#922d7b">

<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta property="twitter:creator" content="<%= content_for?(:twitter_creator) ? content_for(:twitter_creator) : "BloggerApp" %>" />


<!-- Google / Search Engine Tags -->
<meta itemprop="name" content="<%= content_for?(:title) ? content_for(:title) : "BloggerApp" %>">
<meta itemprop="description" content="<%= content_for?(:description) ? content_for(:description) : "BloggerApp description" %>">