config/routes.rb
Rails.application.routes.draw do

	root 'blogs#index'

	devise_for :users, controllers: {registrations: "users/registrations"}
	
	resources :blogs do
		member do
			resources :comments do
				get :view_replies
			end
			post :upvote
		end

		collection do
			get :my_blogs
		end
	end
end

app/models/blog.rb
class Blog < ApplicationRecord
	#
	# associations
	#

	belongs_to :user
	has_one :image, :as => :assetable, :class_name => "Blog::Image", :dependent => :destroy
	has_many :comments,:as => :commentable,:class_name => "Blog::Comment",:dependent => :destroy
	has_many :votes, :as => :votable, :class_name => "Blog::Vote", :dependent => :destroy

	accepts_nested_attributes_for :image, :reject_if => proc { |attributes| attributes[:attachment].blank? } 
	
	#
	# Scopes
	#
    scope :as_created, -> { order(created_at: :desc)}
    
	#
	# validations
	#

	validates :name, :description, :presence => true

	#
	# methods
	#

	def momentize
		self.try(:created_at).try(:iso8601)
	end

	def image_url
		build_image unless image
		image.url(:thumb)
	end

	def upvoted?(user)
        votes.find_by_voter_id( user.id )
    end
end

app/models/blog/comment.rb
class Blog::Comment < Comment
end

app/models/blog/image.rb
class Blog::Image < Asset
    has_attached_file :attachment,
    :styles => {
        :original => {source_file_options: '-auto-orient'},
        :new => {:geometry => "400x300#", :quality => 100, :format => 'jpg'},
        :thumb => {:geometry => "640x480#", :quality => 100, :format => 'jpg'}
        },:default_url => "img_not_available.png",
        :convert_options => {:all => "-quality 100"}
    validates_attachment :attachment, content_type: { content_type: ["image/jpg", "image/jpeg", "image/gif", "image/png"] }
end

app/models/blog/vote.rb
class Blog::Vote < Vote
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :set_blog, only: [:show, :edit, :update, :destroy, :upvote]

	# GET /blogs
	# GET /blogs.json
	def index
		@blogs = Blog.as_created.paginate(page: (params[:page] || 1), per_page: 20)
	end

	# GET /blogs/1
	# GET /blogs/1.json
	def show
	end

	# GET /blogs/new
	def new
		@blog = current_user.blogs.new
	end

	# GET /blogs/1/edit
	def edit
	end

	# POST /blogs
	# POST /blogs.json
	def create
		@blog = current_user.blogs.new(blog_params)

		respond_to do |format|
			if @blog.save
				format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
				format.json { render :show, status: :created, location: @blog }
			else
				format.html { render :new }
				format.json { render json: @blog.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /blogs/1
	# PATCH/PUT /blogs/1.json
	def update
		respond_to do |format|
			if @blog.update(blog_params)
				format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
				format.json { render :show, status: :ok, location: @blog }
			else
				format.html { render :edit }
				format.json { render json: @blog.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /blogs/1
	# DELETE /blogs/1.json
	def destroy
		@blog.destroy
		respond_to do |format|
			format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def my_blogs
		@blogs = current_user.blogs.all.as_created.paginate(page: (params[:page] || 1), per_page: 20)
	end

	def upvote
		@vote = @blog.votes.find_by(voter_id: current_user.id)
		if @vote.present?
			@vote.destroy
		else
			@vote = @blog.votes.create(voter_id: current_user.id)
		end
	end

	private
	
	# Use callbacks to share common setup or constraints between actions.
	def set_blog
		@blog = Blog.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def blog_params
		params.require(:blog).permit(:name, :description, image_attributes: [:id, :attachment])
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/partials/_blog.html.erb
<div class="blog" id="blog-np-<%= blog.id %>">
  <div class="userPic">
    <%= image_tag blog.user.image_url %>
  </div>
  <div class="userInfo">
    <span class="post-user-first_name">
      <%= link_to "javascript:void(0);" do %>
        <%= blog.user.first_name %>
      <% end %>
    </span>
    <span class="post-user-last_name">
      <%= "@#{blog.user.last_name}" %>
    </span>
    <div class="time-stamp-data">
      <%= content_tag :span, class: "blog-timestamp", data: {momentize: blog.momentize, image: image_url("dot-pic.png")}  do %>
      <% end %>
    </div>
  </div>
  <% if blog.user == current_user %>
    <div class="blog-actions" >
        <%= link_to 'Edit', edit_blog_path(blog) %> 
    </div>
  <% end %>
  <div class="blogData">
    <div class="content-blog-text">
      <span class="title">
        <%= blog.name %>
      </span>
      <span class="description">
        <%= simple_format(blog.description.to_s) %>
      </span>
    </div>
    <%if blog.image.present? %>
      <div class="imageData">
        <%= image_tag blog.image_url %>
      </div>
    <% end %>
  </div>
  <div class="likeAndCommentArea_<%= blog.id %> likeAndCommentArea">
    <%= render "blogs/partials/blog_actions", blog: blog %>
  </div>
</div>

app/views/blogs/partials/_blog_actions.html.erb
<ul>
  <li>
    <% if current_user && blog.upvoted?(current_user) %>
      <%= link_to upvote_blog_path(blog, type: :down) , method: :post, remote: :true do %>
        <%= image_tag 'upvoted.svg',class: "upvoted" %>
      <% end %>
    <% else %>
      <%= link_to upvote_blog_path(blog, type: :up), method: :post, remote: :true do %>
        <%= image_tag 'upvote.svg',class: "upvote" %>
      <% end %>
    <% end %>
    <span class="count">
      <%= blog.votes.count %>
    </span>
  </li>
  <li>
    <%= link_to comments_path(blog) do %>
      <%= image_tag 'message.svg',class: "comment" %>
    <% end %>
  </li>
</ul>

app/views/blogs/partials/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <label><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</label>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :name, autofocus: true, placeholder: 'Enter blog title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, autocomplete: "off", cols: 50, rows: 15, placeholder: 'Enter blog content here', class: 'form-control' %>
  </div>

  <%= f.fields_for :image , f.object.image_url do |image_form| %>
      <%= image_form.hidden_field :id %>
      <div class="form-group">
        <%= image_form.file_field :attachment, class: "user-interest-image-file form-control" %>
      </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary", data: {disable_with: "Creating..."} %>
  </div>
<% end %>